fixed undefined reference to table and got rid of python inline code
Python code that produces graphs was removed as it was not refered to
by report and was causing problems which pdflatex not finding
resulting images